SELECT * FROM employees;

SELECT * FROM employees
WHERE SALARY > 50000;

SELECT DEPT, COUNT(*)
FROM employees
GROUP BY DEPT;

SELECT DEPT, AVG(SALARY)
FROM employees
GROUP BY DEPT;

SELECT * FROM employees
ORDER BY SALARY DESC;
